# Generated by Django 4.2.3 on 2023-07-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados', '0001_initial'),
        ('codigoPostal', '0001_initial'),
        ('gradoEstudios', '0001_initial'),
        ('colonias', '0001_initial'),
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidoP', models.CharField(max_length=40)),
                ('apellidoM', models.CharField(max_length=40)),
                ('calle', models.CharField(max_length=60)),
                ('numExt', models.CharField(max_length=5)),
                ('numInt', models.CharField(max_length=5)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colonias.colonias')),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codigoPostal.codigopostal')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estados.estados')),
                ('gradoEstudios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gradoEstudios.gradoestudios')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='municipios.municipios')),
            ],
        ),
    ]
