# Generated by Django 4.2.3 on 2023-07-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros', '0002_alter_centros_codigopostal'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalacionesCentros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centros.centros')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instalaciones.instalaciones')),
            ],
        ),
    ]
