# Generated by Django 4.2.3 on 2023-07-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='apellidoM',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='socios',
            name='numInt',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
