# Generated by Django 4.2.3 on 2023-08-01 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0001_initial'),
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paises.paises'),
        ),
    ]
