# Generated by Django 4.2.3 on 2023-07-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
        ('colonias', '0001_initial'),
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('calle', models.CharField(max_length=60)),
                ('numExt', models.CharField(max_length=5)),
                ('numInt', models.CharField(max_length=5)),
                ('codigoPostal', models.CharField(max_length=5)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colonias.colonias')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estados.estados')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='municipios.municipios')),
            ],
        ),
    ]
