# Generated by Django 4.2.3 on 2023-07-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_alter_centros_codigopostal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centros',
            name='numInt',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
