# Generated by Django 4.2.3 on 2023-08-01 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('estados', '0001_initial'),
        ('colonias', '0001_initial'),
        ('codigoPostal', '0001_initial'),
        ('centros', '0003_alter_centros_numint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centros',
            name='codigoPostal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codigoPostal.codigopostal'),
        ),
        migrations.AlterField(
            model_name='centros',
            name='colonia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colonias.colonias'),
        ),
        migrations.AlterField(
            model_name='centros',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estados.estados'),
        ),
        migrations.AlterField(
            model_name='centros',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='municipios.municipios'),
        ),
    ]
